apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x12zpwsar-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/x12zpwsar-java-quarkus-gitops